version: '3'

services:

  web:
    build: ./web
    depends_on:
      - daemon
    ports:
      - "9054:80"

  db:
    image: postgres
    restart: always
    env_file:
      - database.env # configure postgres

  daemon:
    build: .
    ports:
      - "9050:9050"
      - "9051:9051"
      - "9052:9052"
      - "9053:9053"
